name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: cl.exe GoL.c
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: "*.exe"
        retention-days: 2

  push_to_registry:
    name: ubuntu image build and push
    runs-on: ubuntu-latest
    environment: enviroment
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3     
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: nonagone/devopsexam
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  telegram:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    environment: enviroment
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with: 
          name: my-artifact
          path: my-artifact

      - name: build fail
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Что-то пошло не так. ${{ github.actor }} налажал. Вылезай из Телеги и иди фикси.
            Репа: ${{ github.repository }}

      - name: build succes
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: my-artifact/**
          message: |
            ${{ github.actor }} залил свежий коммит, он кажется даже не сломался:
            
            Репа: ${{ github.repository }}
            
            Изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  # teams:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: download artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: my-artifact
  #         path: my-artifact
  #     - name: send notification
  #       uses: toko-bifrost/ms-teams-deploy-card@master
  #       with:
  #         github-token: ${{ github.token }}
  #         webhook-url: ${{ secrets.MS_TEMAS_WEBHOOK_URL }}
